let perfumeList=[
  {name: 'Royal Mirage', price: 900},
  {name: 'Dark Fever', price: 500},
  {name: 'Good Girl', price: 1900},
  {name: 'Brut', price: 3900},
  {name: 'Every One', price: 990},
  {name: 'Axe', price: 400},
  {name: 'Double Blue', price: 200},
  {name: 'Active Plus', price: 800},
  {name: 'King For Man', price: 1200},
  {name: 'Jaguar Red', price: 1900},
  {name: 'Jaguar Green', price: 2900},
  {name: 'Color Me', price: 480},
  {name: 'Jovan', price: 980},
  {name: 'Yatch Man', price: 590},
  {name: 'Bogart', price: 900},
  {name: 'Royal Spry', price: 480},
  {name: 'Royal Mini', price: 280},
  {name: 'Lafz Spry', price: 180},
  {name: 'Blue Lady', price: 580},
  {name: 'Blue Man', price: 490},
  {name: 'Men Spry', price: 280},
  {name: 'Love Spry', price: 280},
  {name: 'Gold Spry', price: 280},
]

export {perfumeList};